# Generated by Django 5.2.4 on 2025-08-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ["session"],
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзины",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AddField(
            model_name="cart",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Итого",
            ),
        ),
        migrations.AlterModelTable(
            name="cart",
            table="db_cart",
        ),
        migrations.AlterModelTable(
            name="cartitem",
            table="db_cart_item",
        ),
    ]
